### ISSUE TITLE
Delete Skill is causing error in dev

### ISSUE THREAD

**Issue by thebho** [maryvilledev/skilldirectoryui#66]
```
Skills.jsx:81 Uncaught TypeError: this.deleteSkill is not a function
    at Object.value [as shouldDelete] (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:15:545)
    at t (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:7:380)
    at Object.r (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:4:12781)
    at i (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:4:8857)
    at Object.u [as executeDispatchesInOrder] (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:4:9072)
    at f (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:2:25438)
    at m (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:2:25564)
    at Array.forEach (native)
    at n (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:6:12016)
    at Object.processEventQueue (http://ec2-54-147-37-162.compute-1.amazonaws.com:8000/static/js/main.8731b667.js:2:26642)
```

**Comment by thebho** [comment]
Team Members DELETE still works
